#!/bin/bash

# This script can be used as a hook to prevent pulling in changesets that contains third party ad network libraries
# To use, add the following in .hg/hgrc
#
# [hooks]
# pretxnchangegroup.check_libs = ./hooks/check_libs
#

if hg manifest tip | grep '^iphone/AdNetworkLibs' | grep -v 'README$'; then
  echo "ERROR: iphone/AdNetworkLibs must not contain any file other than README"
  exit 1
fi

if hg manifest tip | grep '^android/libs' | grep -v 'README$'; then
  echo "ERROR: android/libs must not contain any file other than README"
  exit 1
fi
